// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home'
    },
    {
      dirName: 'guide',
      type: 'autogenerated',
    },
  ],
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home'
    },
    {
      type: 'category',
      label: 'Requirements',
      link: { type: 'doc', id: 'catalog/requirements/index' },
      items: [{ type: 'autogenerated', dirName: 'catalog/requirements' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'catalog/architecture/index' },
      items: [{ type: 'autogenerated', dirName: 'catalog/architecture' }],
    },
    {
      type: 'category',
      label: 'Development',
      link: { type: 'doc', id: 'catalog/development/index' },
      items: [{ type: 'autogenerated', dirName: 'catalog/development' }],
    },
    {
      type: 'category',
      label: 'Operations',
      link: { type: 'doc', id: 'catalog/operations/index' },
      items: [{ type: 'autogenerated', dirName: 'catalog/operations' }],
    },
    {
      type: 'category',
      label: 'Personas',
      link: { type: 'doc', id: 'personas/index' },
      items: [{ type: 'autogenerated', dirName: 'personas' }],
    },
  ],
};

module.exports = sidebars;
